version: '3.8'

services:
  nodebb:
    build: .
    # image: ghcr.io/nodebb/nodebb:latest
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODEBB_ADDITIONAL_PLUGINS: ./plugins/nodebb-plugin-sso-dingtalk
    depends_on:
      - postgres
    ports:
      - '4567:4567'
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-config:/opt/config
      - ./.env:/usr/src/app/.env:ro
      - ./install/docker/setup.json:/usr/src/app/setup.json

  postgres:
    image: postgres:18.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:8.6.1-alpine
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes', '--loglevel', 'warning']
    # command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"] # uncomment if you want to use snapshotting instead of AOF
    volumes:
      - redis-data:/data
    profiles:
      - redis

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/postgresql

  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/redis

  nodebb-build:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/build

  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/public/uploads

  nodebb-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/config
